title = "mdpan.dev"

# See this for more options: https://github.com/not-matthias/apollo/blob/main/config.toml#L14
# The URL the site will be built for
base_url = "https://mdpan.dev/"

theme = "apollo"
description = "Personal site and blog for Mario Daniel Panuco"

build_search_index = false 
taxonomies = [{ name = "tags" }]
default_language = "en"
generate_feeds = true
minify_html = true 


# hard_link_static = false

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
# build_search_index = true

[markdown]

# When set to "true", emoji aliases translated to their corresponding
# Unicode emoji equivalent in the rendered Markdown files. (e.g.: :smile: => 😄)
# render_emoji = true


# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "ayu-light"

# [search]
# # Whether to include the title of the page/section in the index
# include_title = true
# # Whether to include the description of the page/section in the index
# include_description = false
# # Whether to include the RFC3339 datetime of the page in the search index
# include_date = false
# # Whether to include the path of the page/section in the index (the permalink is always included)
# include_path = false
# # Whether to include the rendered content of the page/section in the index
# include_content = true

# index_format = "elasticlunr_javascript" # or "elasticlunr_json"
#[link_checker]
# internal_level = "warn"

[extra]
theme = "auto"
favicon = "/icons/favicon.ico"

toc = true
use_cdn = false
# favicon = "/icon/favicon.png"
# theme = "toggle"              # light, dark, auto, toggle
comment = false
fancy_code = true
dynamic_note = true           # a note that can be toggled
mathjax = true
mathjax_dollar_inline_enable = true
menu = [
    { name = "/posts", url = "/posts", weight = 1 },
    { name = "/projects", url = "/projects", weight = 2 },
    { name = "/about", url = "/", weight = 3 },
    { name = "resume.pdf", url = "output_filename.pdf", weight = 4 },
    { name = "/tags", url = "/tags", weight = 5 },
]

socials = [
    { name = "twitter", url = "https://twitter.com/roctodp", icon = "twitter" },
    { name = "github", url = "https://github.com/mariodanielpancuo", icon = "github" },
]

custom_css = []
